version: '3'

services:
  app:
    build: .
    image: app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/express-boilerplate
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
    networks:
      - express-boilerplate-network

  mongodb:
    image: docker.io/mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - express-boilerplate-network

volumes:
  dbdata:

networks:
  express-boilerplate-network:
    driver: bridge
